/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellAdvisorRouteImport } from './routes/_shell.advisor'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellExpertRouteImport } from './routes/_shell.expert'
import { Route as ShellForecastRouteImport } from './routes/_shell.forecast'
import { Route as ShellHealthRouteImport } from './routes/_shell.health'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellScanRouteImport } from './routes/_shell.scan'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAdvisorRoute = ShellAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellExpertRoute = ShellExpertRouteImport.update({
  id: '/expert',
  path: '/expert',
  getParentRoute: () => ShellRoute,
} as any)
const ShellForecastRoute = ShellForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHealthRoute = ShellHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScanRoute = ShellScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof ShellAdvisorRoute
  '/dashboard': typeof ShellDashboardRoute
  '/expert': typeof ShellExpertRoute
  '/forecast': typeof ShellForecastRoute
  '/health': typeof ShellHealthRoute
  '/reports': typeof ShellReportsRoute
  '/scan': typeof ShellScanRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof ShellAdvisorRoute
  '/dashboard': typeof ShellDashboardRoute
  '/expert': typeof ShellExpertRoute
  '/forecast': typeof ShellForecastRoute
  '/health': typeof ShellHealthRoute
  '/reports': typeof ShellReportsRoute
  '/scan': typeof ShellScanRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/advisor': typeof ShellAdvisorRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/expert': typeof ShellExpertRoute
  '/_shell/forecast': typeof ShellForecastRoute
  '/_shell/health': typeof ShellHealthRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/scan': typeof ShellScanRoute
  '/_shell/settings': typeof ShellSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/dashboard'
    | '/expert'
    | '/forecast'
    | '/health'
    | '/reports'
    | '/scan'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/dashboard'
    | '/expert'
    | '/forecast'
    | '/health'
    | '/reports'
    | '/scan'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/advisor'
    | '/_shell/dashboard'
    | '/_shell/expert'
    | '/_shell/forecast'
    | '/_shell/health'
    | '/_shell/reports'
    | '/_shell/scan'
    | '/_shell/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/advisor': {
      id: '/_shell/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof ShellAdvisorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/expert': {
      id: '/_shell/expert'
      path: '/expert'
      fullPath: '/expert'
      preLoaderRoute: typeof ShellExpertRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/forecast': {
      id: '/_shell/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ShellForecastRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/health': {
      id: '/_shell/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof ShellHealthRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scan': {
      id: '/_shell/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ShellScanRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdvisorRoute: typeof ShellAdvisorRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellExpertRoute: typeof ShellExpertRoute
  ShellForecastRoute: typeof ShellForecastRoute
  ShellHealthRoute: typeof ShellHealthRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellScanRoute: typeof ShellScanRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdvisorRoute: ShellAdvisorRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellExpertRoute: ShellExpertRoute,
  ShellForecastRoute: ShellForecastRoute,
  ShellHealthRoute: ShellHealthRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellScanRoute: ShellScanRoute,
  ShellSettingsRoute: ShellSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
